### ISSUE TITLE
Link local address

### ISSUE THREAD

**Issue by Kane610** [frawau/aiozeroconf#16]
Hi!

Another question. I have Axis cameras that use bonjour to be discovered, they report both link local address and a normal address, it seems like with this library you can't be sure which one you will get as it will show the one or the other between runs. How would I go about fixing this?

**Comment by frawau** [comment]
Could you run
     python3 -m aiozeroconf -s <service name>

A few times to show me what is happening?.

Also, could it be that it is the camera that advertises services like that?

**Comment by Kane610** [comment]
It seemed to always be the same address running that command.

The cameras have an option to turn it off, but with tools like discovery for OSX it will show both addresses.

**Comment by frawau** [comment]
It could be related to the fact that ServiceInfo only has one IPv4 and one IPv6  associated with it. [This PR](https://github.com/jstasiak/python-zeroconf/pull/170/files#diff-097f7c1b50a4fd63e411b693ff288748R2036) in the original package seems to solve that issue. I will check if I can port it here.

**Comment by Kane610** [comment]
Yes that would be great. What time line do you think this will happen in?

**Comment by frawau** [comment]
Hopefully this WE

**Comment by Kane610** [comment]
Wow that's quick. That would bring support with first release using aiozeroconf. Perfect!

**Comment by frawau** [comment]
Hi,
I spent some quality time with the library trying to solve your problem.  

My tentative fix is in branch dev_ha. Could you try it please.

One thing I noticed is that there is a small issue if you start a listener before you publish a service.  It will get you ServiceInfo as soon as it gets an A or AAAA record.  There is no way to know that there should be more I guess.

Let me know.

Regards,
    François

**Comment by frawau** [comment]
Don't forget to read the commit message...  Non backward compatible change

**Comment by Kane610** [comment]
I will try it out tomorrow 👍🏻. Backwards compatibility isn't an issue yet since we just have it published to dev branch

**Comment by Kane610** [comment]
Unfortunately there is an issue with the Asyncio UDP implementation in python for windows (https://github.com/home-assistant/home-assistant/issues/24115) so we can't use your version of Zeroconf until python 3.8. I will try this out as soon as I've gotten everything reverted and working with the sync zeroconf implementation

**Comment by wiryonolau** [comment]
Any update on advertising on multiple ip address ?

**Comment by frawau** [comment]
Sorry no. The OP drop the ball on this, so I did too.  You can try the develop branch.

**Comment by Kane610** [comment]
I followed up on the interest in revisiting changing to this library but the python-zeroconf has been rewritten to be async so there is no longer any need. So I'll close this issue now.
